### PR TITLE
replacing butternife with viewbinding p-1

### PR DESCRIPTION
**Pull request by yellowHatpro**
What I contributed :
 - I saw the project wasn't having view binding yet, so added view binding in Gradle file
 - Used viewbinding in a few files
 
Problems I faced :
 - I only changed a few files for now, since I was having a problem setting the project up in my local, the reason being Mapbox SDK (I am not able to set it up :(     ), and thus couldn't check the project. Solely dependent on CI for now 🤞🏼 .
 
 
 Please can you help me set up the map box SDK so that I can contribute more  🙏🏼

### CODE REVIEW

**Comment by cdhiraj40** [comment]
hello @yellowHatpro, please create an issue first and do read [Contributor Guidelines](https://github.com/enviroCar/enviroCar-app/blob/master/CONTRIBUTING.md) before creating one.
butterknife has been deprecated and ViewBinding is definitely a good option, but it will still be better if you create an issue where maintainers can check if its needed (for future use too) and also this change will be whole project wise so I think maybe PRs should be file-wise so that other contributors can also pick up some file and get done the work quick and reviewing will way easier for maintainers too. Thanks :)

**Comment by yellowHatpro** [comment]
Ok sir,  will do as you say. Thanks for your guidance.

> I think the build is failing in the master branch you can try changing the branch to develop and Gradle will successfully build

No, I worked on the develope branch only, still, SDK was not working. I tried my best but still couldn't make it work.

**Comment by cdhiraj40** [comment]
> Ok sir, will do as you say. Thanks for your guidance.

I am not a sir, just helping on what I know :)

> No, I worked on the develop branch only, still, SDK was not working. I tried my best but still couldn't make it work.

okay I will check and update on this :)

**Comment by yellowHatpro** [comment]
> > Ok sir, will do as you say. Thanks for your guidance.
> 
> I am not a sir, just a fellow contributor helping you with what I know :)
> 
> > No, I worked on the develop branch only, still, SDK was not working. I tried my best but still couldn't make it work.
> 
> okay, I will check and update on this :)

Thanks a lot bud : )

**Comment by SebaDro** [comment]
Hey @yellowHatpro.

Thanks for your interest in contributing to the enviroCar project. Yes, you are right: Butterknife is deprecated for some time now and there different alternatives for it just as Jetpack View Binding and Data Binding. We already discussed this issue internally and found that switching from Butterknife to View Binding is such a big change that we will handle this in a separate project. Therefore, this task will be part of one of the projects we will provide for GSoC 2022. I you'd like to take part in it, please have a look at our GSoC information page: https://wiki.52north.org/Projects/GSoCForStudents. The final project descriptions will be online, soon.

However, to get the mapbox SDK working you have to create an account for mapbox and place your secret mapbox token in your local gradle.properties file. Please, have a look at https://docs.mapbox.com/android/maps/guides/install/.

For now I will close this pull request. I hope it's OK for you.

**Pull request closed without merging**
