### PR TITLE
Fix #613: Bug: No checking for empty field in Confirm Password

### LINKED ISSUE #613: Bug: No checking for empty field in Confirm Password field in Signup activity
Fix #613 
No checking for the empty field in Confirm Password field in the 
Signup activity. As it is present for other fields in that activity

**ScreenShot**

### PR DESCRIPTION
**Pull request by ritish099**
Fix #613 

**Changes Made**

Now a warning message will be shown if Confirm Password field is left empty as it is shown for other fields

### CODE REVIEW

**Review by asaikarthikeya — COMMENTED** [review]
Empty field warning in confirm password  is only shown if the user has entered at least 1 character in password .

**Comment by ritish099** [comment]
@asaikarthikeya what if the user just click on the Submit button without entering any detail? There should be a warning message for every field, I guess its inappropriate to just leave one field , and if you check other apps they also follow the same stratergy as i have done here

**Comment by arvindnegi1** [comment]
@ritish099 if you closely observe checkPasswordValidity() it is checking for any empty value in confirm password and after if calling to confirmPasswordMatch(String, String) and according to control flow checkConfirmPasswordValidity() is called after checkPasswordValidity() so this is doing the same thing. And if click on submit button it should show error for that you can define else part in checkPasswordValidity() while checking for empty value in password2.
Thanks ;)

**Comment by ritish099** [comment]
@arvindnegi1 Thanks sir

**Comment by asaikarthikeya** [comment]
Superseded by #778

**Pull request closed without merging**
