### PR TITLE
Improved layout for activity_car_selection_newcar_fragment

### PR DESCRIPTION
**Pull request by sidraj000**
Previously buttons were not visible (visible only when clicked).
Padding and styles have been improved.

### CODE REVIEW

**Comment by arvindnegi1** [comment]
Please add screenshot it will be easier for Maintainer to review i guess.

**Comment by sidraj000** [comment]
It looks like this now. Previously the input boxes were visible only when
they were clicked.

**Comment by sidraj000** [comment]
I am attaching a link for the screenshot of the layout.
https://drive.google.com/open?id=1te577uXeGXZnHIl5LO5KyIUA2um8ySHV

**Comment by asaikarthikeya** [comment]
This is improved as a part of GSoC 2020

**Comment by SebaDro** [comment]
The car selection view has been already redesigned, so that I will close your request. Thanks for sharing your ideas @sidraj000 .

**Comment by sidraj000** [comment]
Thanks for your reply!!

**Pull request closed without merging**
