### PR TITLE
Added google playstore Rate this app Dialog prompt

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
Fixes: #697

## Description:

Added a feature to automatically show a prompt to rate this app and to navigate to Google Playstore and also configured the prompt specifically for the release-app.
Currently, the Prompt shows when the app has been installed for a week AND has been launched atleast 2 times. If the user clicks "Remind me Later", the prompt will show up again only after 3 days.
The above configurations can be changed at anytime as Documented.

### Sample demo of Rate this app Dialog prompt:
WhatsApp Video 2021-04-06 at 1 48 31 AM

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@arvindnegi1 @bpross-52n sir can you please review this PR?

**Comment by Akash-Ramjyothi** [comment]
@SebaDro sir please review it.

**Comment by Akash-Ramjyothi** [comment]
@SebaDro @arvindnegi1 @bpross-52n can you please review it before it gets superseded?

**Comment by SebaDro** [comment]
I'm not sure, if we need such a feature. Of course, we could obtain much more ratings for the app which increases it's visibility. However, I personally find such prompts very intrusive. What do you think @bpross-52n ?

**Comment by bpross-52n** [comment]
> I'm not sure, if we need such a feature. Of course, we could obtain much more ratings for the app which increases it's visibility. However, I personally find such prompts very intrusive. What do you think @bpross-52n ?

Good point, now that I have come to think about it.. Lets discuss this some more.

**Comment by SebaDro** [comment]
We internally discussed this feature, but do not find it useful. Therefore, I will close this PR.

**Pull request closed without merging**
