### PR TITLE
Improved Settings screen

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
Fixes: #715

## Description:

Added improved Settings screen by implementing Materialized Icons preceding to every Checkbox options to improve the interactivity, user interface and experience.

## Sample demo of current Settings screen:
ezgif com-gif-maker (8)

## Sample demo of improved Settings screen:
ezgif com-gif-maker (9)

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@arvindnegi1 @bpross-52n sir can you please review this PR?

**Comment by Akash-Ramjyothi** [comment]
@SebaDro sir please review it.

**Comment by Akash-Ramjyothi** [comment]
@SebaDro @arvindnegi1 @bpross-52n can you please review it before it gets superseded?

**Review by asaikarthikeya — APPROVED** [review]
Good work @Akash-Ramjyothi . Lets discuss about this with @SebaDro Sir ;)

**Comment by Akash-Ramjyothi** [comment]
@asaikarthikeya Thank you so much for approving my PR. I am always ready and open for discussions with @SebaDro sir.

**Comment by SebaDro** [comment]
The settings screen appears to be a little bit overloaded with all the big sized buttons in black color. Maybe, decreasing the size and a less saturated would be less intrusive.

**Comment by Akash-Ramjyothi** [comment]
Ok @SebaDro sir, thank you for the suggestion. Please give me some time, I will make the changes and commit them.

**Comment by SebaDro** [comment]
Closed, due to inactivity.

**Pull request closed without merging**
