### PR TITLE
[UI] Improve Loader layout

### PR DESCRIPTION
**Pull request by avikumar15**
With reference to issue #467  , here is a solution to the loader's UI. Now the loader looks like :

newloaderlogin

Earlier the loader looked odd since it was left aligned : 

oldloader

### CODE REVIEW

**Comment by arvindnegi1** [comment]
@avikumar15 I don't see the major difference between the reference you provided. Both looks someway similar.

**Comment by avikumar15** [comment]
Hi @dewall , can you please review the code? :)

**Comment by asaikarthikeya** [comment]
Implemented in #747 .

**Comment by SebaDro** [comment]
Thanks @avikumar15 for your contribution. However, all dialogs with progress bar have been redesigned as part of GSoC, which, unfortunately, makes your implementation outdated. Therefore, I will close this request.

**Pull request closed without merging**
