### PR TITLE
Add a place holder text when no tracks are uploaded 

### LINKED ISSUE #454: Add a place holder text when no tracks are uploaded
Currently the uploaded tracks screen is blank when there are no tracks uploaded. Adding a place holder text would be nice since blank screen doesnt look good and is confusing.

**Current State**

**I would like to work on this issue**

### PR DESCRIPTION
**Pull request by cdhiraj40**
fixes #454

### CODE REVIEW

**Review by SebaDro — COMMENTED** [review]
Your fix overwrites the intended behaviour of showing a certain info when the user is not logged in. But that behaviour should be preserved.

**Comment by cdhiraj40** [comment]
> Your fix overwrites the intended behaviour of showing a certain info when the user is not logged in. But that behaviour should be preserved.

the string "you have to login to see the tracks"?

**Comment by SebaDro** [comment]
#828 has provided a more detailed workflow for handling events such as the user is not logged in or internet is not available. In this context the workflow for showing appropriate background info messages has been adopted. As far as I can tell, this also fixes #454. Therefore, I would like to close this PR for the moment.

If you find that there is still an issue with showing the "no tracks" background info, please, open this PR again, but take into account the latest changes.

**Comment by cdhiraj40** [comment]
> #828 has provided a more detailed workflow for handling events such as the user is not logged in or internet is not available. In this context the workflow for showing appropriate background info messages has been adopted. As far as I can tell, this also fixes #454. Therefore, I would like to close this PR for the moment.
> 
> If you find that there is still an issue with showing the "no tracks" background info, please, open this PR again, but take into account the latest changes.

It's totally working and it's a way better approach than mine. :)

**Pull request closed without merging**
