### PR TITLE
Scrollbar for Car Selection screen

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
Fixes: #718

## Description:

Added themed Scrollbar for the Car Selection screen to improve the user interface of the android application. The scrollbar is not static/fixed. It fades away if not used for a few seconds. The scrollbar is a component of AndroidX and no 3rd party library is used which increases the compatibility of the component in the app. The scrollbar will only appear if items exceed the screen size as of to improve user's ease of access. The length of scrollbar is not fixed and varies according to the entities present

## Sample demo of current Car Selection screen:
ezgif com-gif-maker (10)

## Sample demo of Car Selection screen with Scrollbar:
ezgif com-gif-maker (11)

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@arvindnegi1 @bpross-52n sir can you please review this PR?

**Comment by Akash-Ramjyothi** [comment]
@SebaDro sir please review it.

**Comment by Akash-Ramjyothi** [comment]
@SebaDro @arvindnegi1 @bpross-52n can you please review it before it gets superseded?

**Comment by SebaDro** [comment]
This PR only provides minor style improvements, which are not considered. Therefore, I will close it.

**Pull request closed without merging**
