### PR TITLE
Fixed #663 Error message is changed.Also added german translation

### LINKED ISSUE #663: Fueling Empty field
**Issue** :- In add fueling option when we click on tick with empty field the error message is cannot be blank.

**How will I fix this issue** :- Basically, to make it more responsive I will change the error message to this is a mandatory field. By usinng this message it will be more impactful to show a error.

Fueling_Error

**I will be working on this issue**

### PR DESCRIPTION
**Pull request by Bhavya-22**
For logbook Fueling I changed the message from cannot be blank to this is a mandatory field (for more impact of error).

### CODE REVIEW

**Review by arvindnegi1 — COMMENTED** [review]
please change corresponding german translation.

**Comment by Bhavya-22** [comment]
Sir I will do for that is it ok to use Google translate from English to German

**Comment by Bhavya-22** [comment]
Sir, I have also added a german translation. Please review this.

**Comment by asaikarthikeya** [comment]
Superseded by #765

**Pull request closed without merging**
