### PR TITLE
Add a place holder text when no tracks are uploaded

### LINKED ISSUE #454: Add a place holder text when no tracks are uploaded
Currently the uploaded tracks screen is blank when there are no tracks uploaded. Adding a place holder text would be nice since blank screen doesnt look good and is confusing.

**Current State**

**I would like to work on this issue**

### PR DESCRIPTION
**Pull request by cdhiraj40**
fixes #454

### CODE REVIEW

**Comment by cdhiraj40** [comment]
https://user-images.githubusercontent.com/75211982/133624776-c7381fcb-a3f6-4ac0-ab4b-c2345676102b.mp4

**Comment by cdhiraj40** [comment]
The merge conflict is about ```@override```I commented it cause I didn't know which superclass to use with. If anyone can explain me I shall change the code and commit. Thank you.

**Comment by asaikarthikeya** [comment]
> The merge conflict is about `@override`
> The reason I commented it is because I didn't know which superclass to use with. If anyone can explain me I shall change the code and commit again. Thank you.

Hey, Could you check now. Any `@override` works .

**Comment by asaikarthikeya** [comment]
@cdhiraj40 You can squash all commits into 1 commit. Many thanks for bringing this into notice. :)

**Comment by cdhiraj40** [comment]
> > The merge conflict is about `@override`
> > The reason I commented it is because I didn't know which superclass to use with. If anyone can explain me I shall change the code and commit again. Thank you.
> 
> Hey, Could you check now. And `@override` is for showNoTracksInfo() method.

so since you changed and added @override do I have to do anything?

**Comment by cdhiraj40** [comment]
> @cdhiraj40 You can squash all commits into 1 commit. Many thanks for bringing this into notice. :)

the earlier 3?
 actually, that's only 1 commit another one I did revert so that didn't change anything.

**Comment by asaikarthikeya** [comment]
> > > The merge conflict is about `@override`
> > > The reason I commented it is because I didn't know which superclass to use with. If anyone can explain me I shall change the code and commit again. Thank you.
> > 
> > 
> > Hey, Could you check now. And `@override` is for showNoTracksInfo() method.
> 
> so since you changed and added @override do I have to do anything?

Nope, PR looks good to me. Just sqaush the commits after that this can be merged.

**Comment by asaikarthikeya** [comment]
> > @cdhiraj40 You can squash all commits into 1 commit. Many thanks for bringing this into notice. :)
> 
> the earlier 3?
> actually, that's only 1 commit another one I did revert so that didn't change anything.
> sorry I didn't get what you saying

Yes, Although it did not changed any part of code. It is a good practice to keep the commits that have code changes. Main branch should only contain commits that are relevant. Hope this clears the doubts :)

**Comment by cdhiraj40** [comment]
> > > @cdhiraj40 You can squash all commits into 1 commit. Many thanks for bringing this into notice. :)
> > 
> > 
> > the earlier 3?
> > actually, that's only 1 commit another one I did revert so that didn't change anything.
> > sorry I didn't get what you saying
> 
> Yes, Although it did not changed any part of code. It is a good practice to keep the commits that have code changes. Main branch should only contain commits that are relevant. Hope this clears the doubts :)

yes, that totally makes sense. I will do it asap. Thanks for the help

**Comment by cdhiraj40** [comment]
@asaikarthikeya I guess I did it. you can add that @override again

**Comment by asaikarthikeya** [comment]
> > > > @cdhiraj40 You can squash all commits into 1 commit. Many thanks for bringing this into notice. :)
> > > 
> > > 
> > > the earlier 3?
> > > actually, that's only 1 commit another one I did revert so that didn't change anything.
> > > sorry I didn't get what you saying
> > 
> > 
> > Yes, Although it did not changed any part of code. It is a good practice to keep the commits that have code changes. Main branch should only contain commits that are relevant. Hope this clears the doubts :)
> 
> yes, that totally makes sense. I will do it asap. Thanks for the help

No hurry @cdhiraj40 . This PR might not be merged immediately as @SebaDro sir is working on the contribution guildlines. @SebaDro When will be the new guildlines be released so that we can accept new developers contributions?

**Comment by asaikarthikeya** [comment]
> @asaikarthikeya I guess I did it. you can add that @override again

You can resolve the conflicts in a new commit. No problem :)

**Comment by SebaDro** [comment]
If you would consider, rebasing your PR on the current develop branch I'm willing to merge it :-)

**Comment by cdhiraj40** [comment]
> If you would consider, rebasing your PR on the current develop branch I'm willing to merge it :-)

Hey I think I did it. you can check.
(if it didn't happen can you tell me what do I do because I did update my develop & issue454 branch )

**Comment by SebaDro** [comment]
Do a `git rebase` and afterwards a force push to your issue branch

**Comment by cdhiraj40** [comment]
> Do a `git rebase` and afterwards a force push to your issue branch

it shows``` Everything up-to-date ```

**Comment by SebaDro** [comment]
Your commits contain changes that are already present in the develop branch. Your pull request should only contain all *new* changes. If rebasing is not possible, please, consider creating a new pull request.

**Comment by cdhiraj40** [comment]
> Your commits contain changes that are already present in the develop branch. Your pull request should only contain all *_new_ *changes. If rebasing is not possible, please, consider creating a new pull request.

sorry for the inconvenience I will make a new PR for the issue. Thanks for the help :)

**Comment by asaikarthikeya** [comment]
> > Your commits contain changes that are already present in the develop branch. Your pull request should only contain all *_new_ *changes. If rebasing is not possible, please, consider creating a new pull request.
> 
> sorry for the inconvenience I will make a new PR for the issue. Thanks for the help :)
> Can I close this now?

Yes, you can close this and create a new PR with the relavent code changes. Thanks.

**Pull request closed without merging**
