### PR TITLE
Add bin icon to delete car in my cars screen

### PR DESCRIPTION
**Pull request by Jdbarad**
https://user-images.githubusercontent.com/93068379/175763089-17575158-b158-4468-93c8-eb734e8dba37.mp4
@SebaDro

### CODE REVIEW

**Comment by Jdbarad** [comment]
@SebaDro sir Review this PR.

**Comment by SebaDro** [comment]
Thanks @Jdbarad for your revision. I really like the text marquee feature, so I'm willing to accept it. However, just consider some small adjustments before merge:
1. Rebase your feature branch from develop if not already done
2. Change your pull request so that it will be merged into develop
3. Keep the context menu for deleting and selecting single cars that will pop up when clicking on a single car row
4. Add the full car name to the context menu. This will show users the full car name without having to select a car for activating the marquee feature.

To implement the last point, just set a title and content on the existing [MaterialDialog.Builder](https://github.com/enviroCar/enviroCar-app/blob/51390f033e18c1e1dd2a09a1c9597e676bae353c/org.envirocar.app/src/org/envirocar/app/views/carselection/CarSelectionListAdapter.java#L153). If you want to, you can also replace the `com.afollestad.materialdialogs.MaterialDialog` by [SimpleDialog](https://material.io/components/dialogs/android#simple-dialog) which uses the `com.google.android.material.dialog.MaterialAlertDialogBuilder`. We introduced the `MaterialAlertDialogBuilder` some time ago, so this step will unify the UI a bit more.

**Comment by Jdbarad** [comment]
@SebaDro Sir, New PR #924 is Ready for Review.

**Comment by Jdbarad** [comment]
https://user-images.githubusercontent.com/93068379/175918733-d1c59131-e353-46a8-9287-7b21928dbbf3.mp4

@SebaDro Sir Now Everything is Updated.

**Comment by SebaDro** [comment]
Well, the text marquee feature should only be active for the selcted car. Otherwise the user would be distracted by too many animations. By clicking on a car item, the user now can see the full car name in the MaterialDialog. That's quite sufficient. So please, just consider a last revision.

**Comment by Jdbarad** [comment]
@SebaDro Sir, PR Updated

**Comment by SebaDro** [comment]
I think you forgot to push it.

**Pull request merged**
