### PR TITLE
Fixed #661 Dialog dismiss after 10 seconds with a message.Added german translation

### LINKED ISSUE #661: Bluetooth connection problem
**Issue** :- For bluetooth connection the dialog box is loading but neither it able to connect nor it fails.

**How will I fix this issue** :- I will set a waiting time of 10 seconds for that box after 10 second the box will dismiss box with snackbar message unable to connect.

**I will work on this issue**

### PR DESCRIPTION
**Pull request by Bhavya-22**
Made dialog dismiss after 10 seconds when Start Track button is clicked with a Snackbar message of Unable to connect.

### CODE REVIEW

**Review by arvindnegi1 — CHANGES_REQUESTED** [review]
add corresponding german translation in /values-de/strings_fragment_dashboard.xml

**Comment by Bhavya-22** [comment]
Sir, I have also added a german translation. Please review this.

**Comment by asaikarthikeya** [comment]
Fixed by #752

**Comment by SebaDro** [comment]
As @asaikarthikeya already mentioned, your proposed feature has been superseded by #752, so that will close this request. Anyway, thanks for your contribution.

**Pull request closed without merging**
