### PR TITLE
SendLogFileActivity does not support closing the keyboard when clicking in the background. 

### LINKED ISSUE #803: ```SendLogFileActivity```  does not support closing the keyboard when clicking in the background.

### PR DESCRIPTION
**Pull request by cdhiraj40**
fixes #803

### CODE REVIEW

**Comment by cdhiraj40** [comment]
okay finally. you can check @asaikarthikeya.

**Comment by asaikarthikeya** [comment]
@cdhiraj40 Great that you figure this out, And the implementation LGTM. As, I have previously mentioned to you about the PR merge, new contribution guildlines are in progress and this PR will be rechecked and merged in 1-2 weeks. You can continue to work on other issues if you wish to, by creating another branch from develop. ;)

**Comment by cdhiraj40** [comment]
@asaikarthikeya yes sure this time i won't forget about the branch ;-)

**Comment by cdhiraj40** [comment]
@asaikarthikeya  I have a better approach to handle this and the approach can take care of all the fragments once added to the parent activity.

**Pull request closed without merging**
