### PR TITLE
Improved Materialization in Sign-In Activity

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
## Description:
Improved the materialization of the Sign-In Activity by replacing the existing `AppCompatEditText` with `TextInputEditText` to make it more consistent when compared to other Google android apps for a better user interface.

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@asaikarthikeya please review my PR.

**Comment by asaikarthikeya** [comment]
Hello @Akash-Ramjyothi, Kindly add screenshots so that we could see the visual changes that you have made.Thanks

**Comment by Akash-Ramjyothi** [comment]
## Screenshot of current Sign-In Activity:


## Screenshot of Materialized Sign-In Activity:

**Comment by asaikarthikeya** [comment]
@Akash-Ramjyothi Here, The whole UI of the sign-in and signup has to be updated. Kindly refer to #796. If you would like to work on this then please provide a complete UI mock up. Thanks :)

**Pull request closed without merging**
