### PR TITLE
Selected car type and obd adapter set according to indicators.

### PR DESCRIPTION
**Pull request by asaikarthikeya**
#572 
Car type -

https://user-images.githubusercontent.com/70392921/106921664-3c24c300-6732-11eb-9520-3f8c772010e5.mp4

Bluetooth - 

https://user-images.githubusercontent.com/70392921/106928697-75acfc80-6739-11eb-8e28-b273affe758c.mp4

### CODE REVIEW

**Comment by asaikarthikeya** [comment]
@bpross-52n  please review the changes. Thankyou

**Comment by asaikarthikeya** [comment]
Will make this pull request with base to develop.

**Comment by asaikarthikeya** [comment]
Re-based onto gsoc2021. Updated the PR.

**Review by SebaDro — CHANGES_REQUESTED** [review]
There is another case, which effects in a remaining OBD adapter selection: delete your selected bluetooth device and go back to the dashboard and you wil notice, that the deleted device is still selected. We should fix it also in this pull request.

**Comment by asaikarthikeya** [comment]
> There is another case, which effects in a remaining OBD adapter selection: delete your selected bluetooth device and go back to the dashboard and you wil notice, that the deleted device is still selected. We should fix it also in this pull request.

Resolved by the previous commit. 

https://user-images.githubusercontent.com/70392921/126637521-9107450b-4bc5-440b-bfbf-e382d60ab8b0.mp4

**Review by SebaDro — APPROVED** [review]

**Pull request merged**
