### PR TITLE
Fixed #428 Login,Register,Logout made as icons

### LINKED ISSUE #428: Drop down menu enhancement
**Description of Issue-**
The drop down menus(both logged out and logged states) have just one option, so replacing that drop-down menu with an icon menu might enhance UX. 
 
**Solution**
- Add the required drawables. 
- Set up those drawables in menus as icons and set showAsAction.

**Would you like to work on this ?** Yes.

### PR DESCRIPTION
**Pull request by Bhavya-22**
Made login, register, logout as icons (login and register as different also) with text enabled i.e. on long press the text/title corresponding to each icon will be shown. Also for icons I have used vector assets.

### CODE REVIEW

**Comment by Bhavya-22** [comment]
@arvindnegi1 Sir please review it

**Comment by Akash-Ramjyothi** [comment]
@Bhavya-22 thank you for your contributions, I can see that you have Implemented the icons on the `menu_dashboard`. Can you please provide a Screenshot of the changes made in the Interface  for easy review? Also, it would be great if you have used Material Icons in case you haven't.

**Comment by Bhavya-22** [comment]
Basically, I have used vector assets as they can manage themselves according to different pixels or resolutions.

**Comment by Bhavya-22** [comment]
Here are the screenshots requested by you. Please let me know if any other things are required. Also, sorry for such a late reply.
Login_Icon

Logout_Icon

**Comment by Bhavya-22** [comment]
I will merge all my PRs regarding sign in and sign out page and commit all on one PR.

**Comment by asaikarthikeya** [comment]
@Bhavya-22  This enhancement is not required in the current state of the App. Hence i am closing this. Feel free to ask if you have any doubts. Thank you.

**Pull request closed without merging**
