### PR TITLE
Fixed Add Fueling screen

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
Fixes: #728

## Description:

Added materialized icons for all input fields relevant to the Title to improve consistency and user interface of the Add Fueling screen.

## Screenshot of current Add Fueling screen:
WhatsApp Image 2021-04-09 at 1 40 50 AM

## Screenshot of fixed Add Fueling screen:
WhatsApp Image 2021-04-09 at 2 31 07 AM

### CODE REVIEW

**Comment by Akash-Ramjyothi** [comment]
@arvindnegi1 @bpross-52n sir can you please review this PR?

**Comment by Akash-Ramjyothi** [comment]
@SebaDro sir please review it.

**Comment by Akash-Ramjyothi** [comment]
@SebaDro @arvindnegi1 @bpross-52n can you please review it before it gets superseded?

**Review by asaikarthikeya — APPROVED** [review]
LGTM. Thank you @Akash-Ramjyothi for this PR. I have spoke to @SebaDro about this PR. Sir also liked this UI improvement, We will definitely merge this PR in coming weeks ;)

**Comment by jaimehta1912** [comment]
@asaikarthikeya Thank you so much for approving my work and for the update too.

**Comment by Akash-Ramjyothi** [comment]
@asaikarthikeya Thank you so much for your approval and for the update. I hope it gets Merged and not Superseded :).

**Review by SebaDro — APPROVED** [review]

**Pull request merged**
