### PR TITLE
Drop-down menu enhancements

### LINKED ISSUE #428: Drop down menu enhancement
**Description of Issue-**
The drop down menus(both logged out and logged states) have just one option, so replacing that drop-down menu with an icon menu might enhance UX. 
 
**Solution**
- Add the required drawables. 
- Set up those drawables in menus as icons and set showAsAction.

**Would you like to work on this ?** Yes.

### PR DESCRIPTION
**Pull request by Sarthak2601**
**Fixes #428** 

- Added the required drawable. 
- Set up those drawables in the menus. 

**Screenshots** : Attached

IMG_20200216_234604
Screenshot_2020-02-16-23-44-54-512_org envirocar app

### CODE REVIEW

**Comment by Sarthak2601** [comment]
Hi @dewall, please review.

**Comment by dewall** [comment]
Hi Sarthak, I'll review it soon ;) stay tuned!

**Comment by Sarthak2601** [comment]
> Hi Sarthak, I'll review it soon ;) stay tuned!

Okay :) 
Also please check #427. 
Thanks !

**Comment by asaikarthikeya** [comment]
This enhancement is not required in the current state of the App. Hence i am closing this issue. Feel free to ask if you have any doubts. Thank you.

**Pull request closed without merging**
