### PR TITLE
Optimisation: Replacing listView in CarSelectionActivity with Recycler View

### PR DESCRIPTION
**Pull request by Jdbarad**
https://user-images.githubusercontent.com/93068379/204893791-9715716f-ff0f-4745-b0f6-e152ef72d9fc.mp4

### CODE REVIEW

**Comment by Jdbarad** [comment]
###Description
This activity presently contains listView for showing the list of cars which is not an efficient approach.
This listView needs to be replaced with RecyclerView having well-designed CardViews which will lead to a better user interface as well as better app performance.

###How did it get fixed?
Replace ListView with RecyclerView, Create `CarSelectionRecyclerAdapter` for `mCarRecyclerView` 
Create a function & method that is also required in `CarSelectionListAdapter`. Also added CardView for a better user experience.

###Conclusion 
Now, `CarSelectionActivity` uses RecyclerView, That better for App performance. Also Solved Broken car selection radio button #927 

###Reviews
I like to invite @SebaDro Sir & @asaikarthikeya sir to review this PR and give me suggestions

**Comment by Jdbarad** [comment]
@SebaDro Sir Please Review this PR

**Comment by Jdbarad** [comment]
@SebaDro is this issue fixed in another commit? or Any problem with this PR?

**Comment by SebaDro** [comment]
Hi @Jdbarad,

due to several activities around the GSoC projects the last years, we postponed this pull request, since it was not clear in which extend the issue would have been adressed otherwise. However, the pull request is still valid. So, if you would rebase the pull request to the develop branch and change the target branch to develop, I will take care of it.

**Comment by Jdbarad** [comment]
Sure, I will make a changes and get back to you.

**Pull request closed without merging**
