### PR TITLE
Added no car found image and animation : issue solved #655

### PR DESCRIPTION
**Pull request by niish03**
When there is no selected or added cars in car section there will a blank page so added animation with guidence text

Issue solved : #655 

Added checks at listners too so when user add car it will disappear and when user delete car it will appear again.
Before: 

After:
  #@Screenshot_20210322-210804

### CODE REVIEW

**Comment by asaikarthikeya** [comment]
I was working on this @niish03. You should confirm before working on the issue.

**Review by asaikarthikeya — COMMENTED** [review]
duplicate

**Comment by arvindnegi1** [comment]
@niish03 You can not use any image from anywhere it will have copyright issues. If this is free images then I am sure attribution is required without its not possible.

**Comment by asaikarthikeya** [comment]
Superseded by #770

**Pull request closed without merging**
