### PR TITLE
Dialog when car is deleted

### LINKED ISSUE #585: Display AlertDialog to confirm deletion of car.
**Actual Behaviour**

When user clicks Delete option , car is deleted without further reconfirmation.

**Expected Behaviour**

AlertDialog to verify the confirmation to delete .

https://user-images.githubusercontent.com/70392921/109454529-7015ae80-7a7a-11eb-82c5-c70a442bcc28.mp4

### PR DESCRIPTION
**Pull request by asaikarthikeya**
Fixes #585 

 ### **Changes**

1. Added white image of car( Top-Left of dialog , Please refer the below attached image)
2. Alert dialog to confirm deletion of car. 

### **Working** 

https://user-images.githubusercontent.com/70392921/109501341-77aa7700-7abd-11eb-8b57-4cc95d2b1724.mp4

### **Dialog**

Screenshot (Mar 1, 2021 7_03_42 PM)

### CODE REVIEW

**Comment by asaikarthikeya** [comment]
@bpross-52n please review the changes sir. Thankyou

**Comment by bpross-52n** [comment]
@asaikarthikeya Please follow our [Contributor License Agreement (CLA) guidelines](https://52north.org/software/licensing/guidelines/) if you have not done so already. We would need a signed CLA in order to accept contributions. Thanks!

**Comment by asaikarthikeya** [comment]
@bpross-52n Sure sir.I have signed the License Agreement ,Will post it as soon as possible.

**Comment by bpross-52n** [comment]
@asaikarthikeya Great, thanks!

**Comment by asaikarthikeya** [comment]
Hello sir. Is it possible to send the CLA as a scanned copy instead of post
? I have gone through the FAQs, Would like to reconfirm.Thank you.

**Comment by asaikarthikeya** [comment]
@bpross-52n Sir, please review the changes. Thankyou.

**Comment by asaikarthikeya** [comment]
MaterialAlertDialogBuilder should be used instead of Alertdialog. Will update this PR.

**Pull request closed without merging**
